// Package app contains gorag application use cases.
package app

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"
)

const defaultVersion = "0.1.0-dev"

// Config contains application-level configuration
type Config struct {
	Verbose bool
}

// App coordinates application use cases.
type App struct {
	config Config
}

// New creates an application instance.
func New(config Config) *App {
	return &App{
		config: config,
	}
}

// Manifest describes one gorag artifact generation run.
type Manifest struct {
	Version       string    `json:"version"`
	VaultPath     string    `json:"vaultPath"`
	OutputDir     string    `json:"outputDir"`
	GeneratedAt   time.Time `json:"generatedAt"`
	IncludeHidden bool      `json:"includeHidden"`
}

// ScanInput contains parameters for the scan use case.
type ScanInput struct {
	VaultPath     string
	OutputDir     string
	IncludeHidden bool
}

// ScanOutput contains paths generated by the scan use case.
type ScanOutput struct {
	ManifestPath string
}

// ValidateInput contains parameters for the validate use case.
type ValidateInput struct {
	OutputDir string
}

// ValidateOutput contains validation results.
type ValidateOutput struct {
	ManifestPath string
}

// StatsInput contains parameters for the stats use case.
type StatsInput struct {
	OutputDir string
}

// StatsOutput contains generated artifact statistics.
type StatsOutput struct {
	Manifest Manifest
}

// Scan initializes a gorag artifact directory for a vault.
func (a *App) Scan(ctx context.Context, input ScanInput) (*ScanOutput, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}

	vaultPath, err := filepath.Abs(input.VaultPath)
	if err != nil {
		return nil, fmt.Errorf("resolve vault path: %w", err)
	}

	outputDir, err := filepath.Abs(input.OutputDir)
	if err != nil {
		return nil, fmt.Errorf("resolve output path: %w", err)
	}

	info, err := os.Stat(vaultPath)
	if err != nil {
		return nil, fmt.Errorf("read vault path: %w", err)
	}

	if !info.IsDir() {
		return nil, fmt.Errorf("vault path is not a directory: %s", vaultPath)
	}

	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return nil, fmt.Errorf("create output directory: %w", err)
	}

	manifest := Manifest{
		Version:       defaultVersion,
		VaultPath:     vaultPath,
		OutputDir:     outputDir,
		GeneratedAt:   time.Now().UTC(),
		IncludeHidden: input.IncludeHidden,
	}

	manifestPath := filepath.Join(outputDir, "manifest.json")
	if err := writeJSON(manifestPath, manifest); err != nil {
		return nil, err
	}

	return &ScanOutput{
		ManifestPath: manifestPath,
	}, nil
}

// Validate checks the basic generated artifact structure.
func (a *App) Validate(ctx context.Context, input ValidateInput) (*ValidateOutput, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}

	manifestPath := filepath.Join(input.OutputDir, "manifest.json")

	if _, err := os.Stat(manifestPath); err != nil {
		return nil, fmt.Errorf("manifest not found: %w", err)
	}

	return &ValidateOutput{
		ManifestPath: manifestPath,
	}, nil
}

// Stats reads the current generated artifact manifest.
func (a *App) Stats(ctx context.Context, input StatsInput) (*StatsOutput, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}

	manifestPath := filepath.Join(input.OutputDir, "manifest.json")

	data, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil, fmt.Errorf("read manifest: %w", err)
	}

	var manifest Manifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		return nil, fmt.Errorf("decode manifest: %w", err)
	}

	return &StatsOutput{
		Manifest: manifest,
	}, nil
}

func writeJSON(path string, value any) error {
	file, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create json file: %w", err)
	}
	defer file.Close()

	encoder := json.NewEncoder(file)
	encoder.SetIndent("", "  ")

	if err := encoder.Encode(value); err != nil {
		return fmt.Errorf("encode json file: %w", err)
	}

	return nil
}
